unique_ids:
  assets:
    standard-page.html: J2VL32T5GNOEAHMQ46MUKOULSGLVDJEZ
    theme.css: WTVL567DKAWGETEZRE2PAFB4DPA6J4OX
  forms:
    Form1: 6ZCGRPIIL7M24VW4JW6RUTFZBWCHI3OV
  modules: {}
  scripts: {}
  server_modules: {}
